### PR TITLE
Update dkan_migrate_base.install

### PR DESCRIPTION
**Pull request by acouch**
Acceptance:
- [ ] Adds a 'modified' fied to and instance of the migration map table to be used as a high-water mark.

### CODE REVIEW

**Comment by dkinzer** [comment]
This test is brittle, yesterday it wasn't working at all because `$file` kept returning `false`;

**Comment by acouch** [comment]
Is there a reason not to follow the DKAN convention of `test` as the test folder and having the `composer.json` file in `test`? https://github.com/NuCivic/dkan/blob/7.x-1.x/test/composer.json

I think the composer.json file in the test folder makes more sense because it is only necessary for testing. We could use `require-dev` if we really want that in the root folder https://getcomposer.org/doc/04-schema.md#require-dev

I think following conventions here as much as possible is the best.

**Comment by dkinzer** [comment]
I think the convention is to have composer.json be at the root directory of the project.

I follow the drush project example on this one since they are ahead of the curve where it comes to a lot of this stuff.

Also calling the tests from outside the root ensures that all files get called with one command.

**Comment by dkinzer** [comment]
You're right about the composer.json file.  I changed it when I was trying some different things to get all tests to run and then I forgot to check whether I needed any of those changes at all.

I still think that the `composer.json` file belongs at the root level.  Not only is this more common in other projects but I came to it naturally:

When I tried running the `phpunit` command from outside the `tests` folder in order to run the entire test suite at once, `phpunit` went ahead and tested all tests included in any project that was inside the `vendor` folder.  By putting the composer.json file outside of the tests folder, the vendor folder will also be created outside of the tests folder which means we can run the our suit of tests without needing to perform any acrobatics.

**Comment by dkinzer** [comment]
@acouch we need acceptance test for pull request of @dafeder will not look at it.

**Comment by acouch** [comment]
@dkinzer can you clean up the history?

**Comment by acouch** [comment]
@dkinzer Do you want to work on the `Acceptance Test`?

**Comment by dkinzer** [comment]
Sure... I merged squased the commits to clean up and added `git commit --amend --author acouch --author dkinzer` but that didn't seem to have an affect on author.

**Pull request merged**
