### PR TITLE
Test for data json migration highwater

### PR DESCRIPTION
**Pull request by teosibileau**
- Adds highwater test for data.json migration

### CODE REVIEW

**Comment by janette** [comment]
@drkloc  can you look at this: PHP Fatal Error - Call to a member function getDestination() on a non-object in /home/ubuntu/dkan_migrate_base/dkan_migrate_base/tests/DKANMigrateBaseTest.php on line 331

nucivic_dkan_migrate_base__102_-_circleci_

**Comment by janette** [comment]
@drkloc we are moving all tests into core can you apply these changes to the consolidation branch: https://github.com/NuCivic/dkan/pull/1387

**Comment by teosibileau** [comment]
will do

**Comment by teosibileau** [comment]
This is working properly. It also solves an og_group_ref issue we were having with dkan_harvest on the command line.

**Pull request merged**
